#!/bin/bash

set -ex

export NEUTRON_LBAAS_DASHBOARD_SCREENSHOTS_DIR=/opt/stack/new/f5-lbaas-dashboard/.tox/py27integration/src/horizon/openstack_dashboard/test/integration_tests/integration_tests_screenshots
